# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3da5066ace910b26fe8fd59df68683e9f5d943a5ae65c93f6068b9ad5b34fe080654966b45d6d1db2923098096882996f954b53eaff17c3839d9cd79eaf14e40

test:
  secret_key_base: 07dc2e8ecbad86a6bcf2ba084786f49b7bbf4bf6fccbcd838120df9bc1b28172ad2f9f6d2ec06db2a7d088721cb13d5e6b400bc686d0f26b4949aff0e8bd5081

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
